posts/urls.py
from django.urls import path
from .views import post_commentview,like_unlike_post,PostDeleteView,PostUpdateView

app_name = 'posts'
urlpatterns = [
    path('', post_commentview, name="post_comment_view"),
    path('like/', like_unlike_post, name="like-post"),
    path('<pk>/delete/',PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/',PostUpdateView.as_view(), name="post-update"),
]

profiles/urls.py
from django.urls import path
from . import views


app_name='profiles'
urlpatterns = [
    path('myprofile/' , views.my_profile_view, name="my_profile"),
    path('invites/' , views.invites_received, name="my_invite"),
    path('login/', views.Loginpage, name="login"),
    path('registr_lis/', views.Registration , name="registr_view"),
    path('all_profile/', views.profiles_list_view, name="profiles_view"),
    path('invites_list/', views.invite_profile_list, name="invite_list"),
    path('all-profiles/', views.ProfileListView.as_view(),name="profile_list_view"),
    path('send-invite/', views.send_invatiation , name="send-invite"),
    path('removing_freind/', views.remove_from_friends, name="remove-freind"),
    path('invites/accept/', views.accept_invatition, name="accept-invite"),
    path('invites/reject/', views.reject_invatition , name="reject-invite"),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q


class ProfileManager(models.Manager):
    def get_all_profiles_invites(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = []
        for var in qs:
            if var.status == 'accepted':
                accepted.append(var.receiver)
                accepted.append(var.sender)

        available = [profile for profile in profiles if profile not in accepted]

    def get_all_profile(self,me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User , on_delete=models.CASCADE ,unique=True)
    email = models.EmailField( max_length=200)
    avatar = models.ImageField(default='avatar.png', upload_to='avatar')
    friends = models.ManyToManyField(User, blank=True,related_name='friends')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    objects = ProfileManager()

    
# we have friends
    def get_friends(self):
        return self.friends.all()

# how many freinds we have for calculating
    def get_friends_num(self):
        return self.friends.all().count()    


# how many posts calculations
    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):            #class Post --> related_name=posts
        return self.posts.all()    

# this is number of Likes relationship with posts.Model(app)->class Like
    def get_likes_given_num(self):
        likes = self.like_set.all()
        total_like = 0
        for item in likes:                   #class Post --> related_name=likes
            if item.value == 'Like':
                total_like += 1
        return total_like 


    def get_likes_recieved_no(self):
        posts = self.posts.all()               #class Post --> related_name=posts 
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked    


    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%y')}"

    def save(self, *args,**kwargs):
        ex = False
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name) + '' + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug=slugify(to_slug + '' +str(get_random_code()))
                ex =Profile.objects.filter(slug=to_slug).exists()
        else:
            to_slug = str(self.user)
        self.slug= to_slug
        super().save(*args,**kwargs)            


STATUS_CHOICES=(
    ('send','send'),
    ('accepted','accepted')
)

class RelationshipManager(models.Manager):
    def invatiotion_recieved(self, receiver):
        query = Relationship.objects.filter(receiver=receiver, status='send')
        return query


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE,related_name='sender')
    receiver = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='receiver')
    status = models.CharField(max_length=15,choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

profiles/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ProfileModelForm(forms.ModelForm):
    class Meta:      
        model = Profile
        fields = ['first_name','last_name','avatar']


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User 
		fields = ['username','email','password1','password2']       

profiles/views.py
from django.shortcuts import render, redirect , get_object_or_404
from .models import Profile,Relationship,RelationshipManager
from .forms import ProfileModelForm, CreateUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login
from django.contrib import messages
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.db.models import Q

@login_required(login_url='/accounts/login/')
def my_profile_view(request):
       
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None,instance=profile)
    confirm= False  
    context = {
        'profile':profile,
        'form':form,
        'confirm':confirm
    }

    
    return render(request, 'profiles/myprofile.html',context)


def invites_received(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invatiotion_recieved(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {
        'qs':results,
        'is_empty':is_empty,
    }    

       
    return render(request,'profiles/my_invites.html', context)



def profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profile(user)
    context = {'qs':qs}

    return render(request, 'profiles/profile_list.html', context)


# it is invite friends
def invite_profile_list(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_invites(user)

    context = {'qs':qs}
    return render(request, 'profiles/invite_list.html', context)

def Loginpage(request):
    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, login)
        return redirect('home')
    else:
        return render(request,'registration/login.html') 



def logout_view(request):
    logout(request)
    return redirect('home')



def Registration(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect('login')
    else:    
        form = CreateUserForm()    
        context = {'form':form}
        return render(request, 'registration/signup.html', context)        


# for seeing profile on browser 
class ProfileListView(ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        qs = Profile.objects.get_all_profile(self.request.user)
        return qs


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_rec = Relationship.objects.filter(sender=profile)
        rel_sen = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_rec:
            rel_receiver.append(item.receiver.user)
        for item in rel_sen:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender']  = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] == True     
        return context 


# this is for sending freindship each other
def send_invatiation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        relat = Relationship.objects.create(sender=sender, receiver=receiver,status='send')  
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my_profile')      

# this is deleting freindship 
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.filter((Q(sender=sender) & Q(receiver=receiver)) |(Q(sender=receiver) & Q(receiver=sender)))  
        rel.delete() 
        return redirect(request.META.get('HTTP_REFERER'))
        
    return redirect('profiles:my_profile')      


def accept_invatition(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sende=sender, receiver=receiver)
        if rel.status =='sender':
            rel.status == 'accepted'
            rel.save()
    return redirect('profiles:my_invite')        




def reject_invatition(request):
    if request.method == 'POST':
        pk= request.POST.get('profile+_pk')
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my_invite')    

profiles/templates/profiles/invite_list.html
{% extends "base.html" %}

    {% block title %}
        Invite Friends
    {% endblock title %}

    {% block content %}
        <ul>
            {% for var in qs  %}
              <li>{{var}}</li>
            {% endfor %}
        </ul>
    {% endblock content %}

profiles/templates/profiles/my_invites.html
{% extends "base.html" %}

{% block title %}
    My invation
  
{% endblock title %}

   {% block content %}
     
       {% if is_empty %}
          <h1>no </h1>
       {% endif %}
       
     
        {% for obj in qs %}
         <div class="ui segement">
           <div class="ui grid"> 
                <div class="row">
                    <div class="three wide column"> 
                        <img  class="ui small circular image" src="{{obj.avatar.url}}">
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <br>
                        <a href=""><button class="ui primary button w-big mb-5">See profile</button></a>
                        <form action="{% url 'profiles:accept-invite' %}" method="POST">
                          {% csrf_token %}
                          <input type="text" type="hidden" name="profile_pk" value="{{obj.pk}}">
                          <button type="submit" class="ui positive basic button w-big mb-5"><i class="check icon"></i>Accept</button>
                        </form>

                        <form action="{% url 'profiles:reject-invite' %}" method="POST">
                          {% csrf_token %}
                          <input type="text" type="hidden" name="profile_pk" value="{{obj.pk}}">
                          <button type="submit" class="ui negative basic button w-big mb-5"><i class="close icon"></i>Reject</button>
                        </form>



                    </div>
                </div>
           </div>

         </div>
    {% endfor %}
  
   {% endblock  %}

profiles/templates/profiles/myprofile.html
{% extends 'base.html'%}

    {% block title %}
        My Profile
    {% endblock title %}

    {% block content %}
    <!-- Modal -->
    <div class="ui modal">
        <i class="close icon"></i>
        <div class="header">
          Updated your Profile
        </div>
        <div class="image content">
          <div class="ui medium image">
            <img src="{{profile.avatar.url}}">
          </div>
          <div class="description">
            <div class="ui header">provide some info</div>
            <form action="" method="POST" class="ui" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
               
            
            
          </div>
        </div>
        <div class="actions">
          
          <button class="ui positive right labeled icon button" type="submit">
           Updated
            <i class="checkmark icon"></i>
          </button>
        </form>
        </div>
      </div>
    
    <div class="ui segment">
        {% if confirm %}
        <div class="ui green message">Your profile has been updated</div>
        {% endif %}
        <h3>My profile {{request.user}}</h3>
        <div class="ui grid">
            <div class="row">
                <div class="six wide column ">
                    <img src="{{profile.avatar.url}}" class="ui medium rounded image">

                    <div class="row mt-5">
                        <button class="ui secondary button ">Updated your Profile</button>
                    </div>
                    <div class="row mt-5">
                        
                    </div>
                </div>
                <div class="ten wide column">
                    <table class="ui table">
                        <tbody>
                            <tr>
                                <td>Username</td>
                                <td>{{profile.user}}</td>
                            </tr>
                            <tr>
                                <td>First Name</td>
                                <td>{{profile.first_name}}</td>
                            </tr>
                            <tr>
                                <td>Last Name</td>
                                <td>{{profile.last_name}}</td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>{{profile.email}}</td>
                            </tr>
                            <tr>
                                <td>number of friends</td>
                                <td>{{profile.get_friends_num}}</td>
                            </tr>
                            <tr>
                                <td>number of friends</td>
                                <td>
                                    <ul>
                                        {% for friend in profile.get_friends %}
                                          <li>{{friend}}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                            </tr>
                            <tr>
                                <td>number of posts</td>
                                <td>{{profile.get_posts_no}}</td>
                            </tr>
                            <tr>
                                <td>number of Likes </td>
                                <td>{{profile.get_likes_given_num}}</td>
                            </tr>
                            <tr>
                                <td>recieved Likes</td>
                                <td>{{profile.get_likes_recieved_no}}</td>
                            </tr>
                        </tbody>

                    </table>
                </div>
            </div>
    </div>
    </div>
        
    {% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends "base.html" %}

    {% block title %}
        All profiles
    {% endblock title %}

    {% block content %}

        {% if is_empty %}
            <h2>No profile </h2>
        {% endif %}

        {% for obj in object_list %}
            <div class="ui segment">
                <div class="ui grid">
                    <div class="row">
                        <div class="three wide column">
                            <img src="{{obj.avatar.url}}" class="ui small circular image">
                        </div>
                        <div class="thirteen wide column">
                            <h3>{{obj.user}}</h3>
                           <a href="{% url 'profiles:my_invite' %}">
                            <button class="ui primary button w-big mb-5">See profile</button>
                           </a>

                        
                        <!-- //////////////////////// -->
        {% if obj.user not in rel_receiver and obj.user not in rel_sender    %}               
            <form action="{% url 'profiles:send-invite' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                
                  <button class="ui positive basic button" type="submit"><i class="plus square icon"></i>Add to freinds</button>        
               

                
            </form>
            {% endif %}

            {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                <button class="ui disabled button"><i class="user icon"></i>Waiting for approval</button> 
            {% endif %}



                        <!-- ////////////// -->
                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-freind' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            
                            <button class="ui negative basic button" type="submit"><i class="minus square icon"></i>Remove freinds</button>        
                           
                        </form>
                        {% endif %}

                    </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    
    {% endblock content %}