posts/urls.py
from django.urls import path
from .views import post_commentview,like_unlike_post,PostDeleteView,PostUpdateView

app_name = 'posts'
urlpatterns = [
    path('', post_commentview, name="post_comment_view"),
    path('like/', like_unlike_post, name="like-post"),
    path('<pk>/delete/',PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/',PostUpdateView.as_view(), name="post-update"),
]

profiles/urls.py
from django.urls import path
from . import views


app_name='profiles'
urlpatterns = [
    path('myprofile/' , views.my_profile_view, name="my_profile"),
    path('invites/' , views.invites_received, name="my_invite"),
    path('login/', views.Loginpage, name="login"),
    path('registr_lis/', views.Registration , name="registr_view"),
    path('all_profile/', views.profiles_list_view, name="profiles_view"),
    path('invites_list/', views.invite_profile_list, name="invite_list"),
    path('all-profiles/', views.ProfileListView.as_view(),name="profile_list_view"),
    path('send-invite/', views.send_invatiation , name="send-invite"),
    path('removing_freind/', views.remove_from_friends, name="remove-freind"),
    path('invites/accept/', views.accept_invatition, name="accept-invite"),
    path('invites/reject/', views.reject_invatition , name="reject-invite"),
]

templates/main/home.html
{% extends 'base.html'%}

    {% block title %}
        home
    {% endblock %}


    {% block content %}

    {% endblock %}
       <h3 class="user">Welcome our site , {% if user.is_authenticated %} {{user.username}} {% else %} visitor {% endif %}</h3>
    {% block script %}
   
    {% endblock script %}

templates/main/navbar.html
<div class="ui inverted menu nav mb-7">
    <style>
     .logout{
         color:  #FFD700;
     }
     .login{
         color: #FFD700;
     }
     
    </style>
    <div class="ui container">
        <a href="" class="item">
            <h3>artbook</h3>
        </a>
        
        <a href="{% url 'home'%}" class="item">
            Home
        </a>
        <a href="{% url 'profiles:my_profile'%}" class="item">Profile</a>
        <a href="{% url 'posts:post_comment_view'%}" class="item">Posts</a>
        <a href="{% url 'profiles:profile_list_view'%}" class="item">Suggestion Friends</a>


        <div class="right menu">
            {% if request.user.is_authenticated %}
            <div class="item">
                <div class="ui floating dropdown icon button teal">Friends
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <a href="" class="item">
                            All Profiles
                        </a>
                       

                    </div>

                </div>

            </div>

            <div class="item">
                <form action="" method="GET">
                    <div class="ui action left icon input">
                        <input type="text" name="q" class="prompt" placeholder="name of a friend">
                        <i class="search icon"></i>
                        <button type="submit" class="ui button">Search</button>

                    </div>
                </form>

            </div>
         
             <a href="" class="item">
               <strong>You are logged as {{request.user}}</strong> 
            </a>
            <a href="{% url 'logout'%}" class="ui item">
                Logout
            </a>
            {% else %}
            
            <a href="{% url 'login'%}" class="ui item">
                Login
            </a>    


            {% endif %} 

        </div>
    </div>

</div>