posts/urls.py
from django.urls import path
from .views import post_commentview,like_unlike_post,PostDeleteView,PostUpdateView

app_name = 'posts'
urlpatterns = [
    path('', post_commentview, name="post_comment_view"),
    path('like/', like_unlike_post, name="like-post"),
    path('<pk>/delete/',PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/',PostUpdateView.as_view(), name="post-update"),
]

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile


class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='posts',validators=[FileExtensionValidator(['png','jpg','jpeg'])],blank=True)
    liked = models.ManyToManyField(Profile,blank=True,related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='posts')


    def __str__(self):
        return str(self.content[:20])


    def num_likes(self):
        return self.liked.all().count()


    def num_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created',)


class Comment(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('Like','Like'),
    ('Unlike','Unlike'),
)   

class Like(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE)
    post= models.ForeignKey(Post,on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES,max_length=10)
    update= models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

    

            

posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('content','image')


class CommentModelForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'comments'}))        
    class Meta:
        model = Comment
        fields = ('body',)

posts/views.py
from django.shortcuts import render, redirect
from .models import Post,Like
from profiles.models import Profile
from .forms import PostModelForm , CommentModelForm
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView , DeleteView
from django.urls import reverse_lazy
from django.contrib import messages


@login_required(login_url='/accounts/login/')
def post_commentview(request):
    query_set = Post.objects.all()
    profile = Profile.objects.get(user=request.user)

    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_add = False
    profile = Profile.objects.get(user=request.user)



    if 'submit_p_form' in request.POST:
        p_form = PostModelForm(request.POST ,request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.author = profile
            instance.save()
            p_form = PostModelForm()
            post_add = True


    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()    

    context = {
        'query_set':query_set,
        'profile':profile,
        'p_form':p_form,
        'c_form':c_form,
        'post_add':post_add,
    }
    return render(request, 'posts/main.html', context)


def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)


            like, created = Like.objects.get_or_create(user=profile,post_id=post_id)

            if not created:
                if like.value =='Like':
                    like.value='Unlike'
                else:
                    like.value='Like'
            else:
                like.value='Like'
                            
                post_obj.save()
                like.save()   
    return redirect('posts:post_comment_view')                 



class PostDeleteView(DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('posts:post_comment_view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, 'need to be author for delete')
        return obj    


class PostUpdateView(UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:post_comment_view')

    def form_valid(self,form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add.error(None,"you need to be author for update")
            return super().form_invalid(form)    

posts/templates/posts/delete.html
{% extends "base.html" %}

{% block title %}
  <h4>Delete Post</h4>
{% endblock title %}

    {% block content %}
      {% if messages %}
         {% for message  in messages  %}
             {% if 'warning' in message.tags %}
                <div class="ui negative message">
                    <div class="header">
                        {{message}}
                    </div>
                </div>
             {% endif %}              
         {% endfor %}        
      {% endif %}

      {% if not messages %}
         <div class="ui segment">
            <h3>Delete post?</h3>
            <form action="" method="POST">
                {% csrf_token %}
                <p>Are you sure to delete it ?</p>
                <button type="submit">Delete</button>
            </form>
         </div>
        
      {% endif %}
    {% endblock content %}

posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="eleven wide column">
        {% for var in query_set %}

        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">
                <div class="ui grid">
                    <div class="row">
                        {% ifequal request.user var.author.user %}
                            <a href="{% url 'posts:post-update' var.pk %}"><button class="ui button bwhite-lg ">Update</button></a>
                            <a href="{% url 'posts:post-delete' var.pk %}"><button class="ui button bwhite-lg ">Delete</button></a>
                        {% endifequal %}
                    </div>
                </div>
                    
                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}> 
                {{ var.author.user }} - {{ var.created|timesince}} ago
            </div>
            <div class="ui fluid image">
                {% if var.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content">
                <p> {{ var.content }} </p>
                <div class="right floated">
                    <form action="{% url 'posts:like-post' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{var.id}}>
                        {% if profile not in var.liked.all %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs up icon"></i>
                            </button>
                            <span> {{var.num_likes}} likes</span>
                        {% else %}
                            <button type="submit" class="ui bwhite-sm button"><i class="thumbs down icon"></i>
                            </button>
                            <span> {{var.num_likes}} likes</span>
                        {% endif %}
                    </form>
                </div>
                <i class="comment icon"></i>
                <span> {{ var.num_comments }} comments</span>
            </div>
            <div class="extra content">
                <div class="mb-5">
                  
                </div>
                <button class="cmt_btn ui button mb-5">show / hide comments</button>
                <div class="comment-box">
                {% if var.comment_set.all %}
                    {% for c in var.comment_set.all %}
                    
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{var.id}}>
                    {{ c_form }}
                    <button type="submit" name="submit_c_form" class="ui primary button mt-5 w-full">Send</button>
                </form>
            </div>
        </div>


        {% endfor %}
    </div>
    <div class="five wide column">
        <div class="ui segment">
            {% if post_added %}
                <div class="ui green message">Post added</div>
            {% endif %}
            <form action="" method="POST" class='ui form' enctype="multipart/form-data">
                {% csrf_token %}
                {{p_form}}
                <button type='submit' name="submit_p_form" class="ui positive button w-full mt-5">Send</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });
        });
    </script>
{% endblock scripts %}

posts/templates/posts/update.html
{% extends "base.html" %}
{% block title %}
  <h4>Update post</h4>
{% endblock title %}

    {% block content %}
      <div class="ui segment">
          <h3>Update Post</h3>
            <form action="" method="POST" enctype="multipart/form-data">
               {% csrf_token %}
               {{form}}
               <button class="ui button primary mt-5" type="submit">Update</button>
               
            
            </form>
      </div>
    {% endblock content %}